# Generated by Django 5.0.6 on 2024-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=False, help_text='Der User hat seine Email Adresse verifiziert'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
